[general]
import = [
	"themes/gruvbox-dark-hard-contrast.toml"
]

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
bold = { family = "JetBrainsMonoNerdFont", style = "Bold" }
italic = { family = "JetBrainsMonoNerdFont", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNerdFont", style = "Bold Italic" }
size = 9

[terminal]
shell = "/usr/bin/zsh"
